parameters:
    memberstack_api_key: '%env(MEMBERSTACK_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MemberstackService:
        arguments:
            $memberstackApiKey: '%memberstack_api_key%'
